name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: read
jobs:
  lint:
    strategy:
      matrix:
        go: ['1.17','1.21']
        os: ['ubuntu-latest']
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
  test:
    strategy:
      matrix:
        go: ['1.17','1.21']
        os: ['ubuntu-latest']
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - run: go test -race ./...
